### ISSUE TITLE
Is the current Image prioritised when streaming tiles?

### ISSUE THREAD

**Issue by PolarBean** [Neural-Systems-at-UIO/WebWarp#24]
When I am viewing one of the final images in webalign it takes a long time to load. when i check the network tab its requesting tiles from other images. Is this expected behaviour and can we prioritise the tiles currently being viewed?

**Comment by Tevemadar** [comment]
Zoomer updated in https://github.com/Neural-Systems-at-UIO/WebWarp/commit/651ae57a9ef5d75851cfd040aae82ba7bdebb70d
