### ISSUE TITLE
license & copyright?

### ISSUE THREAD

**Issue by lzehl** [Neural-Systems-at-UIO/WebWarp#27]
maybe it is on purpose but the README states the MIT license but the license file is missing from the repository. Is the license MIT ? and who is the copyright owner and what is the copyright year?

**Comment by Tevemadar** [comment]
Fixed in https://github.com/Neural-Systems-at-UIO/WebWarp/commit/df82c8a2b09a8ae03dc1d9eda3278a154b8e60c8
